export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const TOGGLE_IS_LOGGED = "TOGGLE_IS_LOGGED";
export const UPDATE_CURRENTUSER = "UPDATE_CURRENTUSER";
export const SET_MAINPAGE = "SET_MAINPAGE";
export const HOME_MAINPAGE = "HOME_MAINPAGE";
export const SUPPLIER_MAINPAGE = "SUPPLIER_MAINPAGE";
export const COMPANIES_MAINPAGE = "COMPANIES_MAINPAGE";
export const CONTACTS_MAINPAGE = "CONTACTS_MAINPAGE";
export const ABOUT_MAINPAGE = "ABOUT_MAINPAGE";
export const SET_SELECTEDSUPPLIER = "SET_SELECTEDSUPPLIER";
export const GETSUPPLIERS = "GETSUPPLIERS";

